<?php
$arr=[
    '4shared'=>'https://www.4shared.com/web/q/#query=%s&sort=size%2Cdesc',
    'acronimos'=>'https://www.acronymfinder.com/~/search/af.aspx?string=exact&Acronym=%s',
    'alexa'=>'https://alexa.com/siteinfo/%s',
    'amazon brasil'=>'https://www.amazon.com.br/s?k=%s&s=price-asc-rank&dc&ref=sr_st_price-asc-rank',
    'antônimos'=>'https://www.antonimos.com.br/busca.php?q=%s',
    'artigos científicos (researchgate)'=>'https://www.researchgate.net/search?q=%s',
    'atom'=>'https://atom.io/packages/search?q=%s',
    'books'=>'https://br1lib.org/s/?q=%s',//https://book4you.org/s/?q=%s
    'britannica'=>'https://escola.britannica.com.br/pesquisa/artigos/%s',
    'buscape'=>'https://www.buscape.com.br/search?page=1&invalidPath=false&sortBy=prod_items_sort_by_price_asc&q=%s&no-shortcut=1',
    'cdnjs'=>'https://cdnjs.com/libraries?q=%s',
    'dailymotion'=>'https://www.dailymotion.com/search/%s/videos',
    'discogs'=>'https://www.discogs.com/search/?q=%s&type=all',
    'docs (em espanhol)'=>'https://www.documaniatv.com/search.php?keywords=%s',
    'docs (nomes em espanhol)'=>'https://www.filmaffinity.com/es/search.php?stext=%s',
    'duck'=>'https://duckduckgo.com/?q=%s&kl=br-pt&ia=web',
    'emojipedia'=>'https://emojipedia.org/search/?q=%s',
    'extensão (firefox)'=>'https://addons.mozilla.org/en-US/firefox/search/?q=%s&type=extension',
    'farmácia (são joão)'=>'https://www.saojoaofarmacias.com.br/search.html?query=%s&type=lowest',
    'fricke'=>'https://www.loja.fricke.com.br/loja/busca.php?palavra_busca=%s',
    'genius'=>'https://genius.com/search?q=%s',
    'geonames'=>'https://www.geonames.org/search.html?q=%s',
    'github'=>'https://github.com/search?q=+%s+&type=repositories',
    'globo play'=>'https://globoplay.globo.com/busca/?q=%s',
    'icon'=>'https://fontawesome.com/icons?d=gallery&p=2&q=%s&s=brands,duotone,light,regular,solid&m=free',
    'imagens (yahoo)'=>'https://br.images.search.yahoo.com/search/images?p=%s&fr2=p%3As%2Cv%3Ai',
    'imdb'=>'https://www.imdb.com/find?q=%s&ref_=nv_sr_sm',
    'infopedia (dicionario)'=>'https://www.infopedia.pt/dicionarios/lingua-portuguesa/%s',        
    'informal'=>'https://www.dicionarioinformal.com.br/%s/',
    'is down'=>'https://www.isitdownrightnow.com/%s.html',
    'jquery'=>'https://api.jquery.com/?s=%s',
    'last.fm'=>'https://www.last.fm/search/tracks?q=%s',
    'letras'=>'https://www.letras.mus.br/?q=%s',    
    'letras (azlyrics)'=>'https://search.azlyrics.com/search.php?q=%s',    
    'limetorrents'=>'https://www.limetorrents.info/search/all/%s/seeds/1/',    
    'mdn'=>'https://developer.mozilla.org/en-US/search?q=%s',
    'maps (google)'=>'https://www.google.com.br/maps?hl=pt&q=%s',
    'mercado livre'=>'https://lista.mercadolivre.com.br/%s/_OrderId_PRICE',
    'mint (software)'=>'https://community.linuxmint.com/software/view/%s',      
    'music'=>'https://music.youtube.com/search?q=%s',
    'news (google)'=>'https://news.google.com/search?q=%s&hl=pt-BR&gl=BR&ceid=BR%3Apt-419',
    'npm'=>'https://www.npmjs.com/search?q=%s',
    'oembed'=>'http://localhost/oembed/index.php?id=%s',
    'packagist'=>'https://packagist.org/?query=%s',
    'php'=>'https://www.php.net/manual-lookup.php?pattern=%s&scope=quickref',
    'quanto custa'=>'https://quantocustaum.com.br/?s=%s',
    'reclameaqui'=>'https://www.reclameaqui.com.br/busca/?q=%s',
    'scihub'=>'https://sci-hub.se/%s',
    'significados'=>'https://www.significados.com.br/?s=%s',
    'sinônimos'=>'https://www.sinonimos.com.br/busca.php?q=%s',
    'so'=>'https://duckduckgo.com/?q=%s+site%3Astackoverflow.com&ia=web',
    'tld'=>'https://tld-list.com/tld/%s',
    'tpb'=>'https://thepiratebay0.org/search/%s/1/99/0',
    'twitter'=>'https://twitter.com/search?q=%s+lang%3Apt%20filter%3Averified&src=typd&f=live&vertical=default',
    'urban dictionary'=>'https://www.urbandictionary.com/define.php?term=%s',
    'username'=>'http://localhost/username/index.php?user=%s',
    'whosampled'=>'https://www.whosampled.com/search/?q=%s',
    'wikipedia'=>'https://duckduckgo.com/?q=%s+site%3Awikipedia.org&ia=web',
];
ksort($arr);
return $arr;
